import asyncio
import json
import os
from contextlib import asynccontextmanager
from pathlib import Path

import httpx
import structlog
import uvicorn
from pydantic import BaseModel
from starlette.applications import Starlette
from starlette.background import BackgroundTask
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Route

from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.apps import A2AStarletteApplication
from a2a.server.events import EventQueue
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.tasks import InMemoryTaskStore, TaskUpdater
from a2a.types import (
    AgentCapabilities,
    AgentCard,
    AgentSkill,
    Part,
    TextPart,
    UnsupportedOperationError,
)
from a2a.utils.parts import get_text_parts
from langchain_core.messages import HumanMessage

from agents.teleport import (
    discover_apps,
    discover_databases,
    start_app_proxy,
    start_db_proxy,
    stop_proxies,
)
from orchestrator.graph import build_orchestrator
from orchestrator.tool_builder import build_tool_from_card

logger = structlog.get_logger()

PORT = int(os.environ.get("AGENT_PORT", 9000))
CONFIG_PATH = Path(os.environ.get("ORCHESTRATOR_AGENTS_CONFIG", "orchestrator/agents.json"))
TSH_DISCOVERY_QUERY = os.environ.get(
    "ORCHESTRATOR_TSH_DISCOVERY_QUERY",
    'labels["app-type"] == "specialist" && labels["demo"] == "ai-agents"',
)
TSH_DB_DISCOVERY_QUERY = os.environ.get(
    "ORCHESTRATOR_TSH_DB_DISCOVERY_QUERY",
    'labels["demo"] == "ai-agents"',
)
DATABASES_CONFIG_PATH = Path(os.environ.get("ORCHESTRATOR_DATABASES_CONFIG", "orchestrator/databases.json"))

# When true, load agents/databases from init-container-generated JSON configs
# (agents.json + databases.json) instead of running tsh discovery + local proxies.
# Set to "true" in the K8s deployment; defaults to false (unset) for local dev.
TUNNEL_MODE = os.environ.get("ORCHESTRATOR_TUNNEL_MODE", "").lower() in ("1", "true", "yes")

# Mutable state — updated on every reload
_state: dict = {"tools": [], "graph": None, "proxies": [], "databases": []}


# ---------------------------------------------------------------------------
# Agent discovery
# ---------------------------------------------------------------------------

async def fetch_agent_card(base_url: str) -> dict:
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.get(f"{base_url.rstrip('/')}/.well-known/agent-card.json")
        resp.raise_for_status()
        return resp.json()


async def _stop_proxies() -> None:
    """Terminate all running proxy processes."""
    await stop_proxies(_state.get("proxies", []))
    _state["proxies"] = []


async def load_tools_from_config() -> list:
    config = json.loads(CONFIG_PATH.read_text())
    tools = []
    for entry in config:
        base_url = entry["url"]
        try:
            card = await fetch_agent_card(base_url)
            tool = build_tool_from_card(card, base_url)
            tools.append(tool)
            logger.info("agent loaded", name=card["name"], url=base_url)
        except Exception as e:
            logger.warning("agent skipped", url=base_url, error=str(e))
    logger.info("tools ready", count=len(tools))
    return tools


def _load_databases_config() -> list[dict]:
    """Load databases.json if it exists (generated by init container or static)."""
    if not DATABASES_CONFIG_PATH.exists():
        return []
    try:
        databases = json.loads(DATABASES_CONFIG_PATH.read_text())
    except Exception:
        return []
    if databases:
        logger.info("databases loaded from config", path=str(DATABASES_CONFIG_PATH),
                     count=len(databases),
                     databases=[d["name"] for d in databases])
    return databases


async def load_tools_from_tunnels() -> list | None:
    """Load agents from tunnel-based agents.json (generated by init container).

    Only used when ``ORCHESTRATOR_TUNNEL_MODE=true`` (set in K8s deployment).
    Returns None when not in tunnel mode, signalling the caller to try
    alternative discovery.
    """
    if not TUNNEL_MODE:
        return None
    if not CONFIG_PATH.exists():
        logger.warning("tunnel mode enabled but agents config not found", path=str(CONFIG_PATH))
        return None
    try:
        config = json.loads(CONFIG_PATH.read_text())
    except Exception:
        return None
    if not config:
        return None

    logger.info("loading agents from tunnel config", path=str(CONFIG_PATH), count=len(config))
    tools = []
    for entry in config:
        base_url = entry["url"]
        name = entry.get("name", base_url)
        try:
            card = await fetch_agent_card(base_url)
            tool = build_tool_from_card(card, base_url)
            tools.append(tool)
            skills = [s["name"] for s in card.get("skills", [])]
            logger.info("agent loaded", name=card["name"], url=base_url, skills=skills)
        except Exception as e:
            logger.warning("agent skipped (tunnel)", name=name, url=base_url, error=repr(e))

    # Load database tunnels from init container config
    _state["databases"] = _load_databases_config()

    tool_summary = {t.name: t.description[:80] for t in tools}
    logger.info("tools ready", count=len(tools), tools=tool_summary)
    return tools


async def load_tools() -> list:
    """Load agent tools using the best available method.

    Priority:
      1. Tunnel-based agents.json (from init container, K8s deployment)
      2. tsh apps ls + tsh proxy app (local dev with Teleport)
      3. Static agents.json fallback
    """
    # Try tunnel-based config first (K8s with init container)
    tunnel_tools = await load_tools_from_tunnels()
    if tunnel_tools is not None:
        return tunnel_tools

    # Try tsh discovery with proxy (local dev)
    await _stop_proxies()
    try:
        app_names = await discover_apps(TSH_DISCOVERY_QUERY)
        logger.info("tsh discovery succeeded", count=len(app_names), apps=app_names,
                     query=TSH_DISCOVERY_QUERY)
    except Exception as e:
        logger.warning("tsh discovery failed, falling back to agents.json", error=str(e))
        return await load_tools_from_config()

    # tsh succeeded but found nothing — fall back to static config
    if not app_names:
        logger.info("no apps discovered via tsh, falling back to agents.json")
        return await load_tools_from_config()

    tools = []
    proxies = []
    for app_name in app_names:
        try:
            local_url, proc = await start_app_proxy(app_name)
            proxies.append(proc)
            card = await fetch_agent_card(local_url)
            tool = build_tool_from_card(card, local_url)
            tools.append(tool)
            skills = [s["name"] for s in card.get("skills", [])]
            logger.info("agent loaded", name=card["name"], url=local_url,
                        proxy_pid=proc.pid, skills=skills)
        except Exception as e:
            logger.warning("agent skipped", app=app_name, error=repr(e))

    # Discover databases via tsh
    databases = []
    try:
        db_list = await discover_databases(TSH_DB_DISCOVERY_QUERY)
        logger.info("tsh db discovery succeeded", count=len(db_list),
                     databases=[d["name"] for d in db_list],
                     query=TSH_DB_DISCOVERY_QUERY)
        for db_info in db_list:
            try:
                local_addr, proc = await start_db_proxy(db_info)
                proxies.append(proc)
                host, port = local_addr.rsplit(":", 1)
                databases.append({
                    "name": db_info["name"],
                    "protocol": db_info.get("protocol", ""),
                    "host": host,
                    "port": int(port),
                    "username": db_info.get("username", ""),
                    "database": db_info.get("database", ""),
                })
            except Exception as e:
                logger.warning("db proxy skipped", db=db_info["name"], error=repr(e))
    except Exception as e:
        logger.warning("tsh db discovery failed", error=str(e))

    _state["proxies"] = proxies
    _state["databases"] = databases
    tool_summary = {t.name: t.description[:80] for t in tools}
    logger.info("tools ready", count=len(tools), tools=tool_summary)
    if databases:
        logger.info("database tunnels ready", count=len(databases),
                     databases=[d["name"] for d in databases])
    return tools


# ---------------------------------------------------------------------------
# Orchestrator A2A executor — reads _state at call time to support hot-reload
# ---------------------------------------------------------------------------

class OrchestratorExecutor(AgentExecutor):
    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        graph = _state["graph"]
        if graph is None:
            raise RuntimeError("Orchestrator graph not initialised")

        updater = TaskUpdater(event_queue, context.task_id, context.context_id)
        user_text = " ".join(get_text_parts(context.message.parts))

        result = await graph.ainvoke(
            {"messages": [HumanMessage(content=user_text)]}
        )

        last_msg = result["messages"][-1]
        response_text = (
            last_msg.content if hasattr(last_msg, "content") else str(last_msg)
        )

        await updater.add_artifact(parts=[Part(root=TextPart(text=response_text))])
        await updater.complete()

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        raise UnsupportedOperationError()


# ---------------------------------------------------------------------------
# /reload endpoint
# ---------------------------------------------------------------------------

class ReloadRequest(BaseModel):
    reason: str


async def do_reload(request: ReloadRequest) -> None:
    try:
        new_tools = await load_tools()
        _state["tools"] = new_tools
        _state["graph"] = build_orchestrator(new_tools)
        logger.info("reload complete", tool_count=len(new_tools), reason=request.reason)
    except Exception as e:
        logger.error("reload failed", error=str(e))


async def reload_endpoint(request: Request) -> JSONResponse:
    data = await request.json()
    req = ReloadRequest(**data)
    logger.info("reload triggered", reason=req.reason)
    return JSONResponse(
        {"status": "accepted", "reason": req.reason},
        status_code=202,
        background=BackgroundTask(do_reload, req),
    )


# ---------------------------------------------------------------------------
# App assembly
# ---------------------------------------------------------------------------

def build_orchestrator_card() -> AgentCard:
    return AgentCard(
        name="A2A Orchestrator",
        description=(
            "Multi-agent orchestrator. Routes questions to the most appropriate "
            "specialist agent (SQL queries, document search, general knowledge) "
            "and returns the result."
        ),
        url=f"http://localhost:{PORT}",
        version="1.0.0",
        defaultInputModes=["text"],
        defaultOutputModes=["text"],
        capabilities=AgentCapabilities(streaming=False),
        skills=[
            AgentSkill(
                id="orchestrate",
                name="Multi-Agent Orchestration",
                description=(
                    "Routes your question to the most appropriate specialist agent "
                    "and returns the result. Handles SQL/data questions, document "
                    "search, and general knowledge queries."
                ),
                tags=["orchestrator", "routing"],
                examples=[
                    "How many orders were placed last month?",
                    "Find documents about GDPR compliance",
                    "Explain the difference between TCP and UDP",
                ],
            )
        ],
    )


@asynccontextmanager
async def lifespan(app):
    _state["tools"] = await load_tools()
    _state["graph"] = build_orchestrator(_state["tools"])
    agents = [t.name for t in _state["tools"]]
    databases = [d["name"] for d in _state.get("databases", [])]
    logger.info("discovered agents", agents=agents, count=len(agents))
    if databases:
        logger.info("discovered databases", databases=databases, count=len(databases))
    logger.info("orchestrator ready", tool_count=len(_state["tools"]),
                db_count=len(databases), port=PORT)
    yield
    await _stop_proxies()


def build_app() -> Starlette:
    handler = DefaultRequestHandler(
        agent_executor=OrchestratorExecutor(),
        task_store=InMemoryTaskStore(),
    )
    a2a = A2AStarletteApplication(
        agent_card=build_orchestrator_card(),
        http_handler=handler,
    )
    app = Starlette(
        lifespan=lifespan,
        routes=[Route("/reload", reload_endpoint, methods=["POST"])],
    )
    a2a.add_routes_to_app(app)
    return app


app = build_app()


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=PORT)
